// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContentInfo
    {
        /// <summary>
        /// Initializes a new instance of the ContentInfo class.
        /// </summary>
        public ContentInfo() { }

        /// <summary>
        /// Initializes a new instance of the ContentInfo class.
        /// </summary>
        public ContentInfo(string mimeType, string mimeTypeName, int sizeInBytes, string encoding = default(string), string mimeTypeGroup = default(string))
        {
            MimeType = mimeType;
            MimeTypeName = mimeTypeName;
            SizeInBytes = sizeInBytes;
            Encoding = encoding;
            MimeTypeGroup = mimeTypeGroup;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mimeTypeName")]
        public string MimeTypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sizeInBytes")]
        public int SizeInBytes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "encoding")]
        public string Encoding { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mimeTypeGroup")]
        public string MimeTypeGroup { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (MimeType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MimeType");
            }
            if (MimeTypeName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MimeTypeName");
            }
        }
    }
}
