// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Error
    {
        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        public Error() { }

        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        public Error(ErrorError errorProperty)
        {
            ErrorProperty = errorProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public ErrorError ErrorProperty { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ErrorProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ErrorProperty");
            }
        }
    }
}
