// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ErrorError
    {
        /// <summary>
        /// Initializes a new instance of the ErrorError class.
        /// </summary>
        public ErrorError() { }

        /// <summary>
        /// Initializes a new instance of the ErrorError class.
        /// </summary>
        public ErrorError(string errorKey = default(string), int? statusCode = default(int?), string briefSummary = default(string), string stackTrace = default(string), string descriptionURL = default(string), string logId = default(string))
        {
            ErrorKey = errorKey;
            StatusCode = statusCode;
            BriefSummary = briefSummary;
            StackTrace = stackTrace;
            DescriptionURL = descriptionURL;
            LogId = logId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorKey")]
        public string ErrorKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "briefSummary")]
        public string BriefSummary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stackTrace")]
        public string StackTrace { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descriptionURL")]
        public string DescriptionURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logId")]
        public string LogId { get; set; }

    }
}
