// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GenericFacetResponse
    {
        /// <summary>
        /// Initializes a new instance of the GenericFacetResponse class.
        /// </summary>
        public GenericFacetResponse() { }

        /// <summary>
        /// Initializes a new instance of the GenericFacetResponse class.
        /// </summary>
        public GenericFacetResponse(string type = default(string), string label = default(string), IList<GenericBucket> buckets = default(IList<GenericBucket>))
        {
            Type = type;
            Label = label;
            Buckets = buckets;
        }

        /// <summary>
        /// The facet type, eg. interval, range, pivot, stats
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// The field name or its explicit label, if provided on the request
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// An array of buckets and values
        /// </summary>
        [JsonProperty(PropertyName = "buckets")]
        public IList<GenericBucket> Buckets { get; set; }

    }
}
