// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A bucket of facet results
    /// </summary>
    public partial class GenericBucket
    {
        /// <summary>
        /// Initializes a new instance of the GenericBucket class.
        /// </summary>
        public GenericBucket() { }

        /// <summary>
        /// Initializes a new instance of the GenericBucket class.
        /// </summary>
        public GenericBucket(string label = default(string), string filterQuery = default(string), object display = default(object), IList<GenericMetric> metrics = default(IList<GenericMetric>), IList<object> facets = default(IList<object>), GenericBucketBucketInfo bucketInfo = default(GenericBucketBucketInfo))
        {
            Label = label;
            FilterQuery = filterQuery;
            Display = display;
            Metrics = metrics;
            Facets = facets;
            BucketInfo = bucketInfo;
        }

        /// <summary>
        /// The bucket label
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// The filter query you can use to apply this facet
        /// </summary>
        [JsonProperty(PropertyName = "filterQuery")]
        public string FilterQuery { get; set; }

        /// <summary>
        /// An optional field for additional display information
        /// </summary>
        [JsonProperty(PropertyName = "display")]
        public object Display { get; set; }

        /// <summary>
        /// An array of buckets and values
        /// </summary>
        [JsonProperty(PropertyName = "metrics")]
        public IList<GenericMetric> Metrics { get; set; }

        /// <summary>
        /// Additional list of nested facets
        /// </summary>
        [JsonProperty(PropertyName = "facets")]
        public IList<object> Facets { get; set; }

        /// <summary>
        /// Additional information of nested facet
        /// </summary>
        [JsonProperty(PropertyName = "bucketInfo")]
        public GenericBucketBucketInfo BucketInfo { get; set; }

    }
}
