// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Scope
    /// </summary>
    public partial class RequestScope
    {
        /// <summary>
        /// Initializes a new instance of the RequestScope class.
        /// </summary>
        public RequestScope() { }

        /// <summary>
        /// Initializes a new instance of the RequestScope class.
        /// </summary>
        public RequestScope(string locations = default(string))
        {
            Locations = locations;
        }

        /// <summary>
        /// The locations to include in the query
        /// . Possible values include: 'nodes', 'versions', 'deleted-nodes'
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public string Locations { get; set; }

    }
}
