// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RequestPagination
    {
        /// <summary>
        /// Initializes a new instance of the RequestPagination class.
        /// </summary>
        public RequestPagination() { }

        /// <summary>
        /// Initializes a new instance of the RequestPagination class.
        /// </summary>
        public RequestPagination(int? maxItems = default(int?), int? skipCount = default(int?))
        {
            MaxItems = maxItems;
            SkipCount = skipCount;
        }

        /// <summary>
        /// The maximum number of items to return in the query results
        /// </summary>
        [JsonProperty(PropertyName = "maxItems")]
        public int? MaxItems { get; set; }

        /// <summary>
        /// The number of items to skip from the start of the query set
        /// </summary>
        [JsonProperty(PropertyName = "skipCount")]
        public int? SkipCount { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.MaxItems < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "MaxItems", 1);
            }
            if (this.SkipCount < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "SkipCount", 0);
            }
        }
    }
}
