// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RequestHighlightFieldsItem
    {
        /// <summary>
        /// Initializes a new instance of the RequestHighlightFieldsItem class.
        /// </summary>
        public RequestHighlightFieldsItem() { }

        /// <summary>
        /// Initializes a new instance of the RequestHighlightFieldsItem class.
        /// </summary>
        public RequestHighlightFieldsItem(string field = default(string), int? snippetCount = default(int?), int? fragmentSize = default(int?), bool? mergeContiguous = default(bool?), string prefix = default(string), string postfix = default(string))
        {
            Field = field;
            SnippetCount = snippetCount;
            FragmentSize = fragmentSize;
            MergeContiguous = mergeContiguous;
            Prefix = prefix;
            Postfix = postfix;
        }

        /// <summary>
        /// The name of the field to highlight.
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "snippetCount")]
        public int? SnippetCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fragmentSize")]
        public int? FragmentSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mergeContiguous")]
        public bool? MergeContiguous { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prefix")]
        public string Prefix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postfix")]
        public string Postfix { get; set; }

    }
}
