// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RequestFilterQueriesItem
    {
        /// <summary>
        /// Initializes a new instance of the RequestFilterQueriesItem class.
        /// </summary>
        public RequestFilterQueriesItem() { }

        /// <summary>
        /// Initializes a new instance of the RequestFilterQueriesItem class.
        /// </summary>
        public RequestFilterQueriesItem(string query = default(string), IList<string> tags = default(IList<string>))
        {
            Query = query;
            Tags = tags;
        }

        /// <summary>
        /// The filter query expression.
        /// For multi-select facets selected facets must be order together
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// Tags used exclude the filters from facet evaluation for
        /// multi-select facet support
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<string> Tags { get; set; }

    }
}
