// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Request that spellcheck fragments to be added to result set rows
    /// The properties reflect SOLR spellcheck parameters.
    /// </summary>
    public partial class RequestSpellcheck
    {
        /// <summary>
        /// Initializes a new instance of the RequestSpellcheck class.
        /// </summary>
        public RequestSpellcheck() { }

        /// <summary>
        /// Initializes a new instance of the RequestSpellcheck class.
        /// </summary>
        public RequestSpellcheck(string query = default(string))
        {
            Query = query;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

    }
}
