// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Localization settings
    /// </summary>
    public partial class RequestLocalization
    {
        /// <summary>
        /// Initializes a new instance of the RequestLocalization class.
        /// </summary>
        public RequestLocalization() { }

        /// <summary>
        /// Initializes a new instance of the RequestLocalization class.
        /// </summary>
        public RequestLocalization(string timezone = default(string), IList<string> locales = default(IList<string>))
        {
            Timezone = timezone;
            Locales = locales;
        }

        /// <summary>
        /// A valid timezone id supported by @see java.time.ZoneId
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// A list of Locales definied by IETF BCP 47.  The ordering is
        /// significant.  The first locale (leftmost) is used for sort and
        /// query
        /// localization, whereas the remaining locales are used for query
        /// only.
        /// </summary>
        [JsonProperty(PropertyName = "locales")]
        public IList<string> Locales { get; set; }

    }
}
