// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A list of pivots.
    /// </summary>
    public partial class RequestPivot
    {
        /// <summary>
        /// Initializes a new instance of the RequestPivot class.
        /// </summary>
        public RequestPivot() { }

        /// <summary>
        /// Initializes a new instance of the RequestPivot class.
        /// </summary>
        public RequestPivot(string key = default(string), IList<RequestPivot> pivots = default(IList<RequestPivot>))
        {
            Key = key;
            Pivots = pivots;
        }

        /// <summary>
        /// A key corresponding to a matching field facet label or stats.
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pivots")]
        public IList<RequestPivot> Pivots { get; set; }

    }
}
