// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Query.
    /// </summary>
    public partial class RequestQuery
    {
        /// <summary>
        /// Initializes a new instance of the RequestQuery class.
        /// </summary>
        public RequestQuery() { }

        /// <summary>
        /// Initializes a new instance of the RequestQuery class.
        /// </summary>
        public RequestQuery(string query, string language = default(string), string userQuery = default(string))
        {
            Language = language;
            UserQuery = userQuery;
            Query = query;
        }

        /// <summary>
        /// The query language in which the query is written. Possible values
        /// include: 'afts', 'lucene', 'cmis'
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// The exact search request typed in by the user
        /// </summary>
        [JsonProperty(PropertyName = "userQuery")]
        public string UserQuery { get; set; }

        /// <summary>
        /// The query which may have been generated in some way from the
        /// userQuery
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Query == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Query");
            }
        }
    }
}
