// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Common query defaults
    /// </summary>
    public partial class RequestDefaults
    {
        /// <summary>
        /// Initializes a new instance of the RequestDefaults class.
        /// </summary>
        public RequestDefaults() { }

        /// <summary>
        /// Initializes a new instance of the RequestDefaults class.
        /// </summary>
        public RequestDefaults(IList<string> textAttributes = default(IList<string>), string defaultFTSOperator = default(string), string defaultFTSFieldOperator = default(string), string namespaceProperty = default(string), string defaultFieldName = default(string))
        {
            TextAttributes = textAttributes;
            DefaultFTSOperator = defaultFTSOperator;
            DefaultFTSFieldOperator = defaultFTSFieldOperator;
            NamespaceProperty = namespaceProperty;
            DefaultFieldName = defaultFieldName;
        }

        /// <summary>
        /// A list of query fields/properties used to expand TEXT: queries.
        /// The default is cm:content.
        /// You could include all content properties using d:content or list
        /// all individual content properties or types.
        /// As more terms are included the query size, complexity, memory
        /// impact and query time will increase.
        /// </summary>
        [JsonProperty(PropertyName = "textAttributes")]
        public IList<string> TextAttributes { get; set; }

        /// <summary>
        /// The default way to combine query parts when AND or OR is not
        /// explicitly stated - includes ! - +
        /// one two three
        /// (one two three)
        /// . Possible values include: 'AND', 'OR'
        /// </summary>
        [JsonProperty(PropertyName = "defaultFTSOperator")]
        public string DefaultFTSOperator { get; set; }

        /// <summary>
        /// The default way to combine query parts in field query groups when
        /// AND or OR is not explicitly stated - includes ! - +
        /// FIELD:(one two three)
        /// . Possible values include: 'AND', 'OR'
        /// </summary>
        [JsonProperty(PropertyName = "defaultFTSFieldOperator")]
        public string DefaultFTSFieldOperator { get; set; }

        /// <summary>
        /// The default name space to use if one is not provided
        /// </summary>
        [JsonProperty(PropertyName = "namespace")]
        public string NamespaceProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultFieldName")]
        public string DefaultFieldName { get; set; }

    }
}
