// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The consistency state of the index used to execute the query
    /// </summary>
    public partial class ResponseConsistency
    {
        /// <summary>
        /// Initializes a new instance of the ResponseConsistency class.
        /// </summary>
        public ResponseConsistency() { }

        /// <summary>
        /// Initializes a new instance of the ResponseConsistency class.
        /// </summary>
        public ResponseConsistency(int? lastTxId = default(int?))
        {
            LastTxId = lastTxId;
        }

        /// <summary>
        /// The id of the last indexed transaction
        /// </summary>
        [JsonProperty(PropertyName = "lastTxId")]
        public int? LastTxId { get; set; }

    }
}
