// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultSetContextSpellcheckItem
    {
        /// <summary>
        /// Initializes a new instance of the ResultSetContextSpellcheckItem
        /// class.
        /// </summary>
        public ResultSetContextSpellcheckItem() { }

        /// <summary>
        /// Initializes a new instance of the ResultSetContextSpellcheckItem
        /// class.
        /// </summary>
        public ResultSetContextSpellcheckItem(string type = default(string), IList<string> suggestion = default(IList<string>))
        {
            Type = type;
            Suggestion = suggestion;
        }

        /// <summary>
        /// Possible values include: 'searchInsteadFor', 'didYouMean'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// A suggested alternative query
        /// </summary>
        [JsonProperty(PropertyName = "suggestion")]
        public IList<string> Suggestion { get; set; }

    }
}
