// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Query results
    /// </summary>
    public partial class ResultSetPaging
    {
        /// <summary>
        /// Initializes a new instance of the ResultSetPaging class.
        /// </summary>
        public ResultSetPaging() { }

        /// <summary>
        /// Initializes a new instance of the ResultSetPaging class.
        /// </summary>
        public ResultSetPaging(ResultSetPagingList list = default(ResultSetPagingList))
        {
            List = list;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "list")]
        public ResultSetPagingList List { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.List != null)
            {
                this.List.Validate();
            }
        }
    }
}
