// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultSetPagingList
    {
        /// <summary>
        /// Initializes a new instance of the ResultSetPagingList class.
        /// </summary>
        public ResultSetPagingList() { }

        /// <summary>
        /// Initializes a new instance of the ResultSetPagingList class.
        /// </summary>
        public ResultSetPagingList(Pagination pagination = default(Pagination), ResultSetContext context = default(ResultSetContext), IList<ResultSetRowEntry> entries = default(IList<ResultSetRowEntry>))
        {
            Pagination = pagination;
            Context = context;
            Entries = entries;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pagination")]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public ResultSetContext Context { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public IList<ResultSetRowEntry> Entries { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Pagination != null)
            {
                this.Pagination.Validate();
            }
            if (this.Context != null)
            {
                this.Context.Validate();
            }
            if (this.Entries != null)
            {
                foreach (var element in this.Entries)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
