// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultBucketsBucketsItem
    {
        /// <summary>
        /// Initializes a new instance of the ResultBucketsBucketsItem class.
        /// </summary>
        public ResultBucketsBucketsItem() { }

        /// <summary>
        /// Initializes a new instance of the ResultBucketsBucketsItem class.
        /// </summary>
        public ResultBucketsBucketsItem(string label = default(string), string filterQuery = default(string), int? count = default(int?), object display = default(object))
        {
            Label = label;
            FilterQuery = filterQuery;
            Count = count;
            Display = display;
        }

        /// <summary>
        /// The bucket label
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// The filter query you can use to apply this facet
        /// </summary>
        [JsonProperty(PropertyName = "filterQuery")]
        public string FilterQuery { get; set; }

        /// <summary>
        /// The count for the bucket
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// An optional field for additional display information
        /// </summary>
        [JsonProperty(PropertyName = "display")]
        public object Display { get; set; }

    }
}
