// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultNode : Node
    {
        /// <summary>
        /// Initializes a new instance of the ResultNode class.
        /// </summary>
        public ResultNode() { }

        /// <summary>
        /// Initializes a new instance of the ResultNode class.
        /// </summary>
        public ResultNode(string id, string name, string nodeType, bool isFolder, bool isFile, DateTime modifiedAt, UserInfo modifiedByUser, DateTime createdAt, UserInfo createdByUser, bool? isLocked = default(bool?), string parentId = default(string), bool? isLink = default(bool?), ContentInfo content = default(ContentInfo), IList<string> aspectNames = default(IList<string>), object properties = default(object), IList<string> allowableOperations = default(IList<string>), PathInfo path = default(PathInfo), SearchEntry search = default(SearchEntry), UserInfo archivedByUser = default(UserInfo), DateTime? archivedAt = default(DateTime?), string versionLabel = default(string), string versionComment = default(string))
            : base(id, name, nodeType, isFolder, isFile, modifiedAt, modifiedByUser, createdAt, createdByUser, isLocked, parentId, isLink, content, aspectNames, properties, allowableOperations, path)
        {
            Search = search;
            ArchivedByUser = archivedByUser;
            ArchivedAt = archivedAt;
            VersionLabel = versionLabel;
            VersionComment = versionComment;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "search")]
        public SearchEntry Search { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "archivedByUser")]
        public UserInfo ArchivedByUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "archivedAt")]
        public DateTime? ArchivedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionLabel")]
        public string VersionLabel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionComment")]
        public string VersionComment { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
            if (this.ArchivedByUser != null)
            {
                this.ArchivedByUser.Validate();
            }
        }
    }
}
