// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultSetContextFacetQueriesItem
    {
        /// <summary>
        /// Initializes a new instance of the ResultSetContextFacetQueriesItem
        /// class.
        /// </summary>
        public ResultSetContextFacetQueriesItem() { }

        /// <summary>
        /// Initializes a new instance of the ResultSetContextFacetQueriesItem
        /// class.
        /// </summary>
        public ResultSetContextFacetQueriesItem(string label = default(string), string filterQuery = default(string), int? count = default(int?))
        {
            Label = label;
            FilterQuery = filterQuery;
            Count = count;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// The filter query you can use to apply this facet
        /// </summary>
        [JsonProperty(PropertyName = "filterQuery")]
        public string FilterQuery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
