// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SearchEntry
    {
        /// <summary>
        /// Initializes a new instance of the SearchEntry class.
        /// </summary>
        public SearchEntry() { }

        /// <summary>
        /// Initializes a new instance of the SearchEntry class.
        /// </summary>
        public SearchEntry(double? score = default(double?), IList<SearchEntryHighlightItem> highlight = default(IList<SearchEntryHighlightItem>))
        {
            Score = score;
            Highlight = highlight;
        }

        /// <summary>
        /// The score for this row
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

        /// <summary>
        /// Highlight fragments if requested and available. A match can happen
        /// in any of the requested field.
        /// </summary>
        [JsonProperty(PropertyName = "highlight")]
        public IList<SearchEntryHighlightItem> Highlight { get; set; }

    }
}
