// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AssociationBody
    {
        /// <summary>
        /// Initializes a new instance of the AssociationBody class.
        /// </summary>
        public AssociationBody() { }

        /// <summary>
        /// Initializes a new instance of the AssociationBody class.
        /// </summary>
        public AssociationBody(string targetId, string assocType)
        {
            TargetId = targetId;
            AssocType = assocType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "targetId")]
        public string TargetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assocType")]
        public string AssocType { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TargetId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TargetId");
            }
            if (AssocType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssocType");
            }
        }
    }
}
