// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChildAssociationBody
    {
        /// <summary>
        /// Initializes a new instance of the ChildAssociationBody class.
        /// </summary>
        public ChildAssociationBody() { }

        /// <summary>
        /// Initializes a new instance of the ChildAssociationBody class.
        /// </summary>
        public ChildAssociationBody(string childId, string assocType)
        {
            ChildId = childId;
            AssocType = assocType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "childId")]
        public string ChildId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assocType")]
        public string AssocType { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ChildId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ChildId");
            }
            if (AssocType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssocType");
            }
        }
    }
}
