// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GroupMembershipBodyCreate
    {
        /// <summary>
        /// Initializes a new instance of the GroupMembershipBodyCreate class.
        /// </summary>
        public GroupMembershipBodyCreate() { }

        /// <summary>
        /// Initializes a new instance of the GroupMembershipBodyCreate class.
        /// </summary>
        public GroupMembershipBodyCreate(string id, string memberType)
        {
            Id = id;
            MemberType = memberType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Possible values include: 'GROUP', 'PERSON'
        /// </summary>
        [JsonProperty(PropertyName = "memberType")]
        public string MemberType { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (MemberType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MemberType");
            }
        }
    }
}
