// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GroupMemberPagingList
    {
        /// <summary>
        /// Initializes a new instance of the GroupMemberPagingList class.
        /// </summary>
        public GroupMemberPagingList() { }

        /// <summary>
        /// Initializes a new instance of the GroupMemberPagingList class.
        /// </summary>
        public GroupMemberPagingList(Pagination pagination = default(Pagination), IList<GroupMemberEntry> entries = default(IList<GroupMemberEntry>))
        {
            Pagination = pagination;
            Entries = entries;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pagination")]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public IList<GroupMemberEntry> Entries { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Pagination != null)
            {
                this.Pagination.Validate();
            }
            if (this.Entries != null)
            {
                foreach (var element in this.Entries)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
