// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GroupBodyUpdate
    {
        /// <summary>
        /// Initializes a new instance of the GroupBodyUpdate class.
        /// </summary>
        public GroupBodyUpdate() { }

        /// <summary>
        /// Initializes a new instance of the GroupBodyUpdate class.
        /// </summary>
        public GroupBodyUpdate(string displayName)
        {
            DisplayName = displayName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
        }
    }
}
