// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GroupMemberPaging
    {
        /// <summary>
        /// Initializes a new instance of the GroupMemberPaging class.
        /// </summary>
        public GroupMemberPaging() { }

        /// <summary>
        /// Initializes a new instance of the GroupMemberPaging class.
        /// </summary>
        public GroupMemberPaging(GroupMemberPagingList list = default(GroupMemberPagingList))
        {
            List = list;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "list")]
        public GroupMemberPagingList List { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.List != null)
            {
                this.List.Validate();
            }
        }
    }
}
