// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GroupPaging
    {
        /// <summary>
        /// Initializes a new instance of the GroupPaging class.
        /// </summary>
        public GroupPaging() { }

        /// <summary>
        /// Initializes a new instance of the GroupPaging class.
        /// </summary>
        public GroupPaging(GroupPagingList list = default(GroupPagingList))
        {
            List = list;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "list")]
        public GroupPagingList List { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.List != null)
            {
                this.List.Validate();
            }
        }
    }
}
