// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class NodeBodyCreateAssociation
    {
        /// <summary>
        /// Initializes a new instance of the NodeBodyCreateAssociation class.
        /// </summary>
        public NodeBodyCreateAssociation() { }

        /// <summary>
        /// Initializes a new instance of the NodeBodyCreateAssociation class.
        /// </summary>
        public NodeBodyCreateAssociation(string assocType = default(string))
        {
            AssocType = assocType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assocType")]
        public string AssocType { get; set; }

    }
}
