// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TrabajoTitulacion.Modelos.CoreAPI
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Pagination
    {
        /// <summary>
        /// Initializes a new instance of the Pagination class.
        /// </summary>
        public Pagination() { }

        /// <summary>
        /// Initializes a new instance of the Pagination class.
        /// </summary>
        public Pagination(long count, bool hasMoreItems, long skipCount, long maxItems, long? totalItems = default(long?))
        {
            Count = count;
            HasMoreItems = hasMoreItems;
            TotalItems = totalItems;
            SkipCount = skipCount;
            MaxItems = maxItems;
        }

        /// <summary>
        /// The number of objects in the entries array.
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long Count { get; set; }

        /// <summary>
        /// A boolean value which is **true** if there are more entities in
        /// the collection
        /// beyond those in this response. A true value means a request with a
        /// larger value
        /// for the **skipCount** or the **maxItems** parameter will return
        /// more entities.
        /// </summary>
        [JsonProperty(PropertyName = "hasMoreItems")]
        public bool HasMoreItems { get; set; }

        /// <summary>
        /// An integer describing the total number of entities in the
        /// collection.
        /// The API might not be able to determine this value,
        /// in which case this property will not be present.
        /// </summary>
        [JsonProperty(PropertyName = "totalItems")]
        public long? TotalItems { get; set; }

        /// <summary>
        /// An integer describing how many entities exist in the collection
        /// before
        /// those included in this list. If there was no **skipCount**
        /// parameter then the
        /// default value is 0.
        /// </summary>
        [JsonProperty(PropertyName = "skipCount")]
        public long SkipCount { get; set; }

        /// <summary>
        /// The value of the **maxItems** parameter used to generate this list.
        /// If there was no **maxItems** parameter then the default value is
        /// 100.
        /// </summary>
        [JsonProperty(PropertyName = "maxItems")]
        public long MaxItems { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
